from typing import Protocol


class DocumentFacade(Protocol):
    def add_heading(self, text: str, level: int) -> None: ...
    def add_table(self, rows: int, cols: int) -> None: ...
    def save(self, path: str) -> None: ...
