"""Django settings for web project.

Generated by 'django-admin startproject' using Django 5.2.15.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/

All environment-varying configuration is read through web.config.Settings.
No literal secrets, host lists, debug flags, or database credentials appear
in this file (ADR-021, FR-001). Missing required variables raise
pydantic.ValidationError at import time (FR-002).
"""

from pathlib import Path

from web.config import Settings

# Instantiate once at module import; raises ValidationError on misconfiguration.
_settings = Settings()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

SECRET_KEY = _settings.django_secret_key
DEBUG = _settings.django_debug
ALLOWED_HOSTS = _settings.django_allowed_hosts


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "web.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "web.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# PostgreSQL via docker-compose `db` service in dev; Cloud SQL injects the
# same env vars in staging/production. All values are required — no defaults
# (FR-006). Database migrations and connectivity are owned by #164.
DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": _settings.postgres_db,
        "USER": _settings.postgres_user,
        "PASSWORD": _settings.postgres_password,
        "HOST": _settings.postgres_host,
        "PORT": _settings.postgres_port,
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


# Transport security — environment-driven, default-off for staging window.
# Risk-accepted per founder decision (2026-06-13); enabled per environment
# at #177. Each generates a check --deploy warning; disposition: D7/D8 in
# specs/161-settings-12-factor-config/research.md.
SECURE_SSL_REDIRECT = _settings.django_secure_ssl_redirect
SECURE_HSTS_SECONDS = _settings.django_secure_hsts_seconds
SESSION_COOKIE_SECURE = _settings.django_session_cookie_secure
CSRF_COOKIE_SECURE = _settings.django_csrf_cookie_secure
